feat: add types for Typescript usage
fastify/restartable pull request #18
Opened 2022-06-10 13:00 UTC by ormuscama

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2022-06-10 13:16 UTC, mcollina requested changes
Thanks for the contribution! Could you add a test using `tsd`? See all other plugins in this org.

2022-06-10 14:42 UTC, ormuscama commented
Yes of course.
I will also move index.d.ts at the same level as index.ts to be closer to what is done in other plugins

2022-06-13 12:52 UTC, mcollina commented on test/types/index.test-d.tsx
> +
Why `.tsx`? Just use `.ts`.

2022-06-13 15:17 UTC, ormuscama commented on test/types/index.test-d.tsx
> +
typo ( was doing some react ...)

2022-06-13 15:19 UTC, mcollina commented on package.json
> +    "test:tsd": "tsd"
```suggestion
    "test": "standard | snazzy && tap test/test.js && tsd"
```

2022-06-13 15:24 UTC, mcollina approved these changes
lgtm

2022-06-13 15:25 UTC, merged